AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  dev-sentinels7-notification-service

  Sample SAM Template for dev-sentinels7-notification-service

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  DevSentinels7NotificationFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: DevSentinels7NotificationFunction/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
      Environment:
        Variables:
          SENTINELS7DBCONNECTIONSTRING: postgres://tsdbadmin:c2lcstu5e40ne7fe@ssjtxd3mkh.pqhane35a5.tsdb.cloud.timescale.com:30475/tsdb?sslmode=require
          TWILIO_ACCOUNT_SID: 
          TWILIO_AUTH_TOKEN: 
          TWILIO_SMS_URL: 
          TWILIO_FROM_NUMBER: 
          MAIN_SERVICE_ARN: 

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  DevSentinels7NotificationFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt DevSentinels7NotificationFunction.Arn
  DevSentinels7NotificationFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt DevSentinels7NotificationFunctionRole.Arn
