on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dev-sentinels7-auth-service/DevSentinels7AuthFunction
    steps:
    - uses: actions/checkout@v2
    - name: Deploy code to Lambda
      uses: qubitro/action-lambda-python-zip@v1.0
      with:
        lambda_function_name: 'dev-sentinels7-auth-service'
        lambda_region: 'us-east-1'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
