name: deploy-py-lambda
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dev-sentinels7-auth-service
    steps:
    - uses: actions/checkout@master
    - name: Deploy code to Lambda
      uses: mariamrf/py-lambda-action@v1.0.0
      with:
        lambda_layer_arn: 'arn:aws:lambda:us-east-1:083603291895:function:dev-sentinels7-auth-service'
        lambda_function_name: 'dev-sentinels7-auth-service'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'
