name: BalenaCloudDev Push

on:
  push:
    # Only run workflow for pushes to specific branches
    branches:
      - develop

jobs:
  balena-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: amingilani/push-to-balenacloud@v1.0.1
      with:
        api-token: ${{secrets.BALENA_API_TOKEN}}
        application-name: ${{secrets.BALENA_DEV_APPLICATION_NAME}}
